[package]
name = "ipv8-rust-tunnels"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
strip = "debuginfo"
debug = "line-tables-only"
codegen-units = 1
lto = true

[lib]
name = "_rust"
crate-type = ["cdylib", "rlib"]

[[test]]
name = "transport"
path = "tests/transport.rs"

[profile.bench]
inherits = "release"

[[bench]]
name = "transport"
path = "benches/transport.rs"
harness = false

[[bench]]
name = "processing"
path = "benches/processing.rs"
harness = false

[[bench]]
name = "speedtest"
path = "benches/speedtest.rs"
harness = false

[[bench]]
name = "production"
path = "benches/production.rs"
harness = false

[[bench]]
name = "hidden_services"
path = "benches/hidden_services.rs"
harness = false

[dependencies]
tokio = { version = "1.43.0", features = ["full", "tracing"] }
tokio-util = { version = "0.7.18", features = ["full"] }
arc-swap = "1.7.1"
socks5-proto = "0.4.1"
socks5-server = "0.10.1"
rand = "0.10.2"
bdecode = "=0.1.0"
deku = "0.19"
openssl = { version = "0.10", features = ["vendored"] }
flume = "0.12.0"
dashmap = "6.2.1"
bencode = "0.1.16"
ffmpeg-next = { version = "9.0", default-features = false, features = ["codec", "format", "software-scaling"], optional = true }

tracing = { version = "0.1", features = ["std"] }
console-subscriber = "0.5.0"
tracing-subscriber = { version = "0.3", features = ["env-filter", "registry", "fmt"] }

pyo3 = { version = "0.29.0", features = ["multiple-pymethods"], optional = true }

[features]
default = ["python-extension", "transcoder"]
pyo3 = ["dep:pyo3"]
python-extension = ["pyo3", "pyo3/extension-module"]
transcoder = ["dep:ffmpeg-next"]
