from typing import Final, Optional, List, Tuple, Any, Dict, Set

__version__: str

class PublicKey:
    """
    A public key class supporting LibNaCLPK (Ed25519), PEM, and DER formats.
    """
    def __init__(self, keystring: bytes) -> None: 
        """Load a public key from LibNaCLPK string, PEM, or DER."""
        ...
    def verify(self, signature: bytes, msg: bytes) -> bool: 
        """Verify a signature for a given message."""
        ...
    def key_to_bin(self) -> bytes: 
        """Export the key to LibNaCLPK binary format or DER."""
        ...
    def key_to_pem(self) -> bytes: 
        """Export the key to PEM format."""
        ...
    def get_signature_length(self) -> int: 
        """Return the expected signature length in bytes."""
        ...
    def get_crypt_pk(self) -> bytes: 
        """Get raw X25519 public key bytes."""
        ...

class PrivateKey:
    """
    A private key class supporting Ed25519 (LibNaCLSK), X25519, and Generic EC.
    """
    def __init__(self, keystring: bytes) -> None: 
        """Load a private key from LibNaCLSK string, PEM, or DER."""
        ...
    @staticmethod
    def generate(curve_name: str) -> "PrivateKey": 
        """Generate a new keypair (e.g., 'ed25519' or a NIST curve)."""
        ...
    def key_to_bin(self) -> bytes: 
        """Export the key to LibNaCLSK binary format or DER."""
        ...
    def key_to_pem(self) -> bytes: 
        """Export the key to PEM format."""
        ...
    def signature(self, msg: bytes) -> bytes: 
        """Sign a message and return the raw signature bytes."""
        ...
    def get_signature_length(self) -> int: ...
    def pub(self) -> PublicKey: 
        """Derive the public key from this private key."""
        ...
    def diffie_hellman(self, peer_public_key: bytes) -> bytes: 
        """Perform X25519 Diffie-Hellman and return the shared secret."""
        ...
    def get_crypt_pk(self) -> bytes: 
        """Get raw X25519 public key bytes."""
        ...

class SessionKeys:
    """Container for HKDF-SHA256 derived keys and salts."""
    kf: bytes  # Key Forward (32 bytes)
    kb: bytes  # Key Backward (32 bytes)
    sf: bytes  # Salt Forward (4 bytes)
    sb: bytes  # Salt Backward (4 bytes)
    counter_f: int
    counter_b: int

class Endpoint:
    """
    High-performance Rust UDP endpoint with SOCKS5 support.
    """
    def __init__(self, listen_addr: str, list_port: int) -> None: ...
    
    def open(self, callback: Any, worker_threads: int) -> bool: 
        """Start the Tokio runtime and bind the socket."""
        ...
    def close(self, timeout_secs: int) -> None: 
        """Gracefully shut down the endpoint."""
        ...
    def is_open(self) -> bool: ...
    def get_address(self) -> Tuple[str, int]: ...
    
    def send(self, address: Tuple[str, int], bytes: bytes) -> None: 
        """Send a raw UDP packet."""
        ...
    def send_cell(self, address: Tuple[str, int], bytes: bytes) -> None: 
        """Encrypt and send a tunnel cell through a circuit, relay, or exit."""
        ...

    def add_circuit(self, circuit_id: int, circuit_obj: Any) -> None: ...
    def update_circuit(self, circuit_id: int, circuit_obj: Any) -> None: ...
    def update_circuit_stats(self, circuit_id: int, circuit_obj: Any) -> None: ...
    def remove_circuit(self, circuit_id: int) -> None: ...

    def add_relay(self, circuit_id: int, relay_obj: Any) -> None: ...
    def update_relay_stats(self, circuit_id: int, relay_obj: Any) -> None: ...
    def remove_relay(self, circuit_id: int) -> None: ...

    def add_exit(self, circuit_id: int, exit_obj: Any) -> None: ...
    def update_exit_stats(self, circuit_id: int, exit_obj: Any) -> None: ...
    def remove_exit(self, circuit_id: int) -> None: ...

    def get_socks5_statistics(self) -> List[Dict[str, Any]]: ...
    def get_socket_statistics(self) -> Tuple[int, ...]: ...
    def get_message_statistics(self, prefix: bytes) -> Dict[int, List[int]]: ...
    def get_byte_counters(self) -> Tuple[int, int]: ...

    def set_prefix(self, prefix: bytes) -> None: ...
    def set_prefixes(self, prefixes: List[bytes]) -> None: ...
    def set_max_relay_early(self, max_relay_early: int) -> None: ...
    def set_peer_flags(self, peer_flags: Set[int]) -> None: ...
    def set_exit_address(self, address: Tuple[str, int]) -> None: ...

    def create_socks5_server(self, port: int, hops: int) -> int: ...
    def set_udp_associate_default_remote(self, address: Tuple[str, int], hops: int) -> None: ...
    def get_associated_circuits(self, port: int) -> Tuple[int, ...]: ...
    def get_peers_for_circuit(self, circuit_id: int) -> List[Tuple[str, int]]: ...
    def run_speedtest(self, circuit_id: int, test_time: int, request_size: int, 
                      response_size: int, target_rtt: int, callback: Any, 
                      callback_interval: int) -> None: ...

class EndpointNotOpenError(Exception): ...
class InvalidAddressError(Exception): ...

def generate_safe_prime(bit_length: int) -> int: 
    """Generate a secure safe prime as a Python integer."""
    ...
def generate_session_keys(shared_secret: bytes) -> SessionKeys: 
    """Expand a shared secret into session keys using HKDF-SHA256."""
    ...
def crypto_auth(key: bytes, message: bytes) -> bytes: 
    """Compute a truncated HMAC-SHA512 (first 32 bytes)."""
    ...
def crypto_auth_verify(tag: bytes, key: bytes, message: bytes) -> bool: 
    """Constant-time verification of an HMAC tag."""
    ...
